kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  labels:
    release: stable
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/pv/mysql
