apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis-ha.fullname" . }}-out
  labels:
{{ include "labels.standard" . | indent 4 }}
  annotations:
  {{- if .Values.serviceAnnotations }}
{{ toYaml .Values.serviceAnnotations | indent 4 }}
  {{- end }}
spec:
  type: NodePort
  ports:
  - name: server
    nodePort: 30379
    port: {{ .Values.redis.port }}
    protocol: TCP
    targetPort: redis
  selector:
    release: {{ .Release.Name }}
    app: {{ template "redis-ha.name" . }}